<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <PackageVersion>2024.6.8.1</PackageVersion>
    <Copyright>Codefarts</Copyright>
    <Company>Codefarts</Company>
    <AssemblyVersion>2024.6.8.1</AssemblyVersion>
    <FileVersion>2024.6.8.1</FileVersion>
    <Title>ViewMessaging GameScreens for MonoGame</Title>
    <Authors>Dean Lunz</Authors>
    <RepositoryType>C#</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/createdbyx/Codefarts.ViewMessaging.git</PackageProjectUrl>
    <RepositoryUrl>https://github.com/createdbyx/Codefarts.ViewMessaging.git</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <DebugSymbols>true</DebugSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Codefarts.AppCore" Version="2024.1.26.5" />
    <PackageReference Include="Codefarts.DependenceyInjection" Version="2023.1.30.5" />
    <PackageReference Include="Codefarts.ScreenManager.MonoGame" Version="2023.2.6.3" />
    <PackageReference Include="Codefarts.ViewMessaging" Version="2024.5.6" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Message Handlers\ShowScreenMessage.cs">
      <Link>Message Handlers\ShowScreenMessage.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="buildhelper &quot;-b:$(ProjectDir)$(ConfigurationName)-PreBuild.xml&quot; &quot;-p:$(ProjectPath)&quot; &quot;-tf:$(TargetFramework)&quot;" />
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="buildhelper &quot;-b:$(ProjectDir)$(ConfigurationName)-PostBuild.xml&quot; &quot;-p:$(ProjectPath)&quot; &quot;-tf:$(TargetFramework)&quot;" />
  </Target>
</Project>